---
sidebar: sidebar 
permalink: oci/add-credentials.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials, oci nss, oracle cloud infrastructure 
summary: 'Adicione as credenciais do Oracle Cloud Infrastructure (OCI) para que o Workload Factory tenha as permissões de que precisa para implantar e gerenciar recursos de nuvem em suas contas do OCI.' 
---
= Adicione as credenciais do Oracle Cloud Infrastructure ao NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Adicione e gerencie as credenciais do seu provedor de nuvem para que o NetApp Workload Factory tenha as permissões necessárias para implantar e gerenciar recursos em suas contas de provedor de nuvem.

link:permissions-oci.html["Permissões para o OCI NetApp Storage Service"]

.Sobre esta tarefa
Você pode adicionar credenciais a uma conta existente do Workload Factory na página Credentials. Isso fornece ao Workload Factory as permissões necessárias para gerenciar recursos e processos em seu ambiente de nuvem.

.Antes de começar
Você precisará de credenciais para fazer login na sua conta do Oracle Cloud Infrastructure.

.Passos
. Faça login no  https://console.netapp.com/["O console do NetApp"^].
. No menu, selecione *Cargas de trabalho* > *Administração* > *Credenciais*.
. Na página Credenciais, selecione *Adicionar credenciais*.
. Na página Add Oracle Cloud Infrastructure NetApp Storage Service credentials, faça o seguinte:
+
.. Em _Configuração de permissões_, selecione as permissões apropriadas para as credenciais do Oracle Cloud Infrastructure NetApp Storage Service. As permissões *Visualizar, planejar e analisar* são as padrão. Essa política de permissões permite que você visualize os pools de storage do OCI NSS, obtenha informações sobre a integridade do sistema, receba a análise well-architected dos seus sistemas e explore oportunidades de economia.
.. Siga as etapas manuais fornecidas usando o Oracle Cloud Console para concluir a configuração de permissões para as credenciais do OCI NSS.
.. Em _Nome das credenciais_, insira o nome que você deseja usar para essas credenciais e insira o OCID da Tenancy.


. Selecione *Add*.


.O que vem a seguir
link:quick-start-oci.html["Guia de início rápido para o Oracle Cloud Infrastructure NetApp Storage Service no NetApp Workload Factory."]
