---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: Descubra as novidades do Workload Factory no NetApp Console, como atualizações e melhorias para gerenciamento de cargas de trabalho, administração de serviços, recursos de storage, permissões e muito mais. 
---
= O que há de novo com o Workload Factory no NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Descubra as novidades do Workload Factory no NetApp Console, como atualizações e melhorias para gerenciamento de cargas de trabalho, administração de serviços, recursos de storage, permissões e muito mais.



[[30-september-2026]]
== 30 de setembro de 2026



[[initial-release-of-oracle-cloud-infrastructure-netapp-storage-service-for-workload-factory]]
=== Lançamento inicial do Oracle Cloud Infrastructure NetApp Storage Service for Workload Factory

A versão inicial do OCI NetApp Storage Service (OCI NSS) para o Workload Factory oferece integração, descoberta de sistemas, gerenciamento de credenciais e criação e associação de links. Para solicitar acesso ao OCI NSS, abra um chamado de suporte com a Oracle.



[[workload-factory-documentation-for-netapp-console-users]]
=== Documentação do Workload Factory para usuários do NetApp Console

Você pode encontrar documentação detalhada do Workload Factory no NetApp Console, incluindo guias para onboarding, descoberta do sistema, gerenciamento de credenciais e criação e associação de links.

link:https://docs.netapp.com/us-en/data-services-workloads/index.html["Documentação do Workload Factory para o NetApp Console"]
