---
sidebar: sidebar 
permalink: gcnv/add-credentials.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials 
summary: Adicione as credenciais do Google Cloud NetApp Volumes para que o Workload Factory tenha as permissões necessárias para implantar e gerenciar recursos de nuvem nas suas contas do Google. 
---
= Adicione as credenciais do Google Cloud NetApp Volumes ao NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Adicione e gerencie as credenciais do seu provedor de nuvem para que o NetApp Workload Factory tenha as permissões necessárias para implantar e gerenciar recursos em suas contas de provedor de nuvem.



[[overview]]
== Visão geral

Você pode adicionar as credenciais do Google Cloud NetApp Volumes na página Credenciais do NetApp console. O console fornece instruções de configuração guiadas e um link para a documentação para que você possa concluir a configuração necessária do Google Cloud e depois retornar para finalizar a adição das credenciais.

Use este fluxo de trabalho para conceder ao Workload Factory as permissões necessárias para descobrir, analisar e gerenciar recursos em seu ambiente do Google Cloud.

A criação das credenciais envolve três etapas:

* Passo 1: selecione o nível de permissões que deseja conceder ao Workload Factory.
* Etapa 2: crie e valide uma conta de serviço do Google Cloud e, em seguida, selecione o projeto do Google Cloud que deseja gerenciar.
* Passo 3: insira um nome para as credenciais e adicione-as.


.Antes de começar
Você precisará de credenciais para fazer login na sua conta do Google Cloud.

.Passos
. Faça login no  https://console.netapp.com/["O console do NetApp"^].
. No menu, selecione *Cargas de trabalho* > *Administração* > *Credenciais*.
. Na página Credenciais, selecione *Adicionar credenciais*.
. Selecione o *Google Cloud NetApp Volumes* como provedor de nuvem.
. Na página Adicionar credenciais do Google Cloud NetApp Volumes, preencha cada seção em *Configuração de permissões*.




[[step-1-create-permission-policies]]
=== Etapa 1: criar políticas de permissão

.Passos
. Em *Criar políticas de permissão*, *Visualizar, planejar e analisar* está selecionado por padrão. Essa política de permissão permite visualizar os pools de armazenamento do Google Cloud NetApp Volumes, obter informações sobre a integridade do sistema, receber a análise de arquitetura adequada para seus sistemas e explorar oportunidades de economia.
. Opcional: selecione *Operações e correção* se também quiser que o Workload Factory gerencie os recursos do Google Cloud NetApp Volumes e corrija problemas de configuração.
. Revise as instruções de configuração em link:https://docs.netapp.com/us-en/storage-management-google-cloud-netapp-volumes/task-set-up-gcnv.html#set-up-a-service-account["Configurar o Google Cloud NetApp Volumes"^] antes de continuar.




[[step-2-create-the-google-cloud-service-account]]
=== Etapa 2: crie a conta de serviço do Google Cloud

.Passos
. Expanda *Configurar seu ambiente do Google Cloud*.
. Conclua os passos 1 a 5 exibidos para criar uma conta de serviço do Google Cloud.
. Copie o endereço de e-mail da conta de serviço.
. Retorne ao Workload Factory, cole o endereço de e-mail no campo *GCP service account* e selecione *Validate credentials*.
. Depois que a validação for concluída, no menu suspenso *Projects*, selecione o projeto do Google Cloud que você deseja que o Workload Factory gerencie. OBSERVAÇÃO: a lista Projects fica indisponível até que as credenciais da conta de serviço sejam verificadas.




[[step-3-enter-the-credentials-name]]
=== Passo 3: insira o nome das credenciais

.Passos
. Expanda *Nome das credenciais*.
. No campo *Nome*, insira um nome para suas credenciais usando apenas caracteres alfanuméricos. Caracteres especiais e espaços não são permitidos.
. Selecione *Add*.


.Resultado
As credenciais do Google Cloud NetApp Volumes foram adicionadas à sua conta e estão disponíveis para operações compatíveis do Workload Factory.
