---
sidebar: sidebar 
permalink: fsx-databases/learn-about-databases.html 
keywords: Databases, FSx for ONTAP, Workload Factory 
summary: NetApp Workload Factory for Databases é um serviço completo de implantação e manutenção de bancos de dados com práticas recomendadas incorporadas para otimização, thin cloning automático e recursos de monitoramento e resolução. 
---
= Saiba mais sobre o NetApp Workload Factory for Databases
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Workload Factory for Databases é um serviço completo de implantação e manutenção de bancos de dados com práticas recomendadas incorporadas para otimização, thin cloning automático e recursos de monitoramento e resolução.



[[what-is-netapp-workload-factory-for-databases]]
== O que é o NetApp Workload Factory for Databases?

NetApp Workload Factory for Databases descobre, avalia, planeja, provisiona e migra dados do Microsoft SQL Server, PostgreSQL e Oracle para implantações do Amazon FSx for NetApp ONTAP (FSx for ONTAP) otimizadas para atender às suas expectativas de desempenho e custo, seguindo as melhores práticas do setor. NetApp Workload Factory for Databases otimiza e gerencia continuamente bancos de dados no FSx for ONTAP.

link:../setup/learn-about-workload-factory.html["Saiba mais sobre o Workload Factory"].



[[workload-factory-benefits-for-self-managed-databases]]
== Benefícios do o Workload Factory para bancos de dados autogerenciados

O Workload Factory oferece as melhores práticas e automação para bancos de dados autogerenciados.



[[best-practices]]
=== Melhores práticas

* Conhecimento integrado da AWS Cloud, do Microsoft Windows e de servidores SQL, e o NetApp ONTAP para implantações de servidores SQL em instâncias EC2.
* Implantação otimizada para o custo total de propriedade.
* Automação de implantação completamente que segue as melhores práticas da AWS, Microsoft e ONTAP.
* O modo de implantação _Criação rápida_ ajuda você a evitar possíveis problemas com a configuração manual.




[[automation-with-workload-factory-codebox]]
=== Automação com o Workload Factory Codebox

O Workload Factory apresenta automação incorporada com o _Codebox_. O Codebox oferece os seguintes benefícios de automação:

* *Geração de trechos de código*: O Workload Factory gera trechos de Infraestrutura como Código (IaC) durante a criação de recursos, permitindo a integração perfeita com fluxos de trabalho de orquestração existentes.
* *Copiloto de infraestrutura como código*: o Codebox é um copiloto de infraestrutura como código (IaC) que ajuda desenvolvedores e DevOps a gerar código para executar qualquer operação compatível com o Workload Factory.
* *Visualizador de código e catálogo de automação*: o Codebox oferece um visualizador de código para análise rápida da automação e um catálogo de automação para reutilização futura rápida.




[[workload-factory-for-databases-features]]
=== Funcionalidades do Workload Factory for Databases

A Workload Factory for Databases oferece os seguintes recursos:

* *Estimativa de custos*: avalie a economia potencial de custos com a Savings calculator, que estima e detalha os custos de storage, computação, licenciamento SQL, snapshot e clone para implantações existentes do Microsoft SQL Server e Oracle com Elastic Block Store, FSx for Windows File Server e ambientes locais, em comparação com o FSx for ONTAP.
* *Implantações simples e rápidas*: simplifique e agilize o provisionamento de hosts, bancos de dados e ambientes de teste com práticas recomendadas incorporadas da NetApp, Microsoft e Amazon, que eliminam a complexidade da configuração manual para instâncias do Microsoft SQL Server e PostgreSQL na AWS.
+
** Faça a implantação a partir do console do Workload Factory usando os modos de criação _Rápido_ ou _Avançado_, ou crie, reutilize e personalize modelos CloudFormation da AWS por meio do Codebox para implantações futuras em vários ambientes.
** Crie bancos de dados isolados sob demanda, com configurações de storage e clones de sandbox que podem ser usados para testes, integração, diagnóstico e treinamento, sem afetar dados de produção.


* *Recurso de avaliação de arquitetura bem projetada*: analise continuamente seus ambientes Microsoft SQL Server e Oracle para obter um relatório abrangente com insights, oportunidades e recomendações que ajudarão você a alcançar excelência operacional, segurança, confiabilidade, eficiência de desempenho e otimização de custos com base nas melhores práticas da AWS.
* *Análise de erros*: analise e solucione erros de log com o analisador de IA para obter mensagens de erro detalhadas, etapas de solução de problemas e recomendações para resolver problemas.
* *Gerenciamento centralizado*: gerencie seus recursos do Microsoft SQL Server, Oracle e PostgreSQL no FSx for ONTAP a partir de um único local. No Workload Factory, visualize a infraestrutura conectada, contas AWS, credenciais, sistemas de arquivos FSx for ONTAP conectados, uso de storage incluindo volumes NFS e LUNs iSCSI, status de proteção, desempenho, status de arquitetura adequada e análise de erros.




[[benefits-of-amazon-fsx-for-ontap-for-self-managed-databases]]
== Benefícios do Amazon FSx for ONTAP para bancos de dados autogerenciados

* *Durabilidade, disponibilidade e confiabilidade*: o FSx for ONTAP oferece diversos recursos que aprimoram a durabilidade e a disponibilidade de bancos de dados autogerenciados hospedados no FSx for ONTAP, como alta disponibilidade com suporte a implantações em zonas de disponibilidade única e múltiplas, Snapshots com reconhecimento de aplicativos, recuperação de desastres aprimorada por meio de replicação e backup eficiente.
* *Desempenho e escalabilidade*: o FSx for ONTAP oferece otimização de desempenho com alta taxa de transferência, baixa latência, conexões de rede de alta velocidade e escalabilidade com múltiplos sistemas de arquivos para escalar o desempenho agregado necessário para uma carga de trabalho.
* *Gerenciamento e eficiência de dados*: o FSx for ONTAP oferece diversos recursos que aprimoram o gerenciamento e a eficiência de dados, como thin clones com uso eficiente de espaço, thin provisioning, compactação e deduplicação, além do armazenamento em camadas de dados acessados com pouca frequência no pool de capacidade.


link:../fsx-storage/learn-fsx-ontap.html["Saiba mais sobre o FSx for ONTAP para o Workload Factory"^].



[[tools-to-use-netapp-workload-factory]]
== Ferramentas para usar o NetApp Workload Factory

Você pode usar o NetApp Workload Factory com as seguintes ferramentas:

* *Workload Factory console*: o Workload Factory console fornece uma visão visual e holística dos seus aplicativos e projetos.
* *NetApp Console*: o NetApp Console oferece uma experiência de interface híbrida para que você possa usar o Workload Factory juntamente com outros serviços de dados da NetApp.
* *Ask me*: use o assistente de IA Ask me para fazer perguntas e saber mais sobre o Workload Factory sem sair do console do Workload Factory. Acesse o Ask me no menu de ajuda do Workload Factory.
* *CloudShell CLI*: o Workload Factory inclui uma CLI do CloudShell para gerenciar e operar ambientes da AWS e da NetApp em várias contas a partir de uma única CLI baseada em navegador. Acesse o CloudShell na barra superior do console do Workload Factory.
* *APIs REST*: use as APIs REST do Workload Factory para implantar e gerenciar seus sistemas de arquivos FSx for ONTAP e outros recursos da AWS.
* *CloudFormation*: Use o código do AWS CloudFormation para executar as ações que você definiu no console do Workload Factory para modelar, provisionar e gerenciar recursos da AWS e de terceiros a partir da pilha do CloudFormation na sua conta AWS.
* *NetApp Terraform provider*: Use o Terraform para criar e gerenciar fluxos de trabalho de infraestrutura gerados no console do Workload Factory.




[[supported-configurations]]
== Configurações suportadas

Você pode usar o Workload Factory com os seguintes mecanismos de banco de dados, versões, sistemas operacionais e modelos de implantação, seguindo as melhores práticas da AWS, NetApp ONTAP, Microsoft SQL Server, Oracle e PostgreSQL.

[cols="1,1,1,1"]
|===
| Mecanismo | Versão | Sistema operacional | Modelo de Implantação 


| Microsoft SQL Server | O SQL Server 2016 | Windows Server 2016 | FCI, Independente 


| Microsoft SQL Server | O SQL Server 2019 | Windows Server 2016 | FCI, Independente 


| Microsoft SQL Server | O SQL Server 2022 | Windows Server 2016 | FCI, Independente 


| Microsoft SQL Server | O SQL Server 2016 | Windows Server 2019 | FCI, Independente 


| Microsoft SQL Server | O SQL Server 2019 | Windows Server 2019 | FCI, Independente 


| Microsoft SQL Server | O SQL Server 2022 | Windows Server 2019 | FCI, Independente 


| Microsoft SQL Server | O SQL Server 2016 | Windows Server 2022 | FCI, Independente 


| Microsoft SQL Server | O SQL Server 2019 | Windows Server 2022 | FCI, Independente 


| Microsoft SQL Server | O SQL Server 2022 | Windows Server 2022 | FCI, Independente 


| Microsoft SQL Server | O SQL Server 2025 | Windows Server 2025 | FCI, Independente 


| Microsoft SQL Server | O SQL Server 2017 | Qualquer | FCI, Independente 


| Microsoft SQL Server | O SQL Server 2016, 2017, 2019, 2022 | Qualquer | FCI, Independente 


| Microsoft SQL Server | O SQL Server 2016, 2017, 2019, 2022 | Qualquer | Grupo de disponibilidade Always On 


| Oracle | 19c | O RHEL, o SuSe Linux | Autônomo (tenant único/múltiplo) 


| Oracle | 21c | O RHEL, o SuSe Linux | Autônomo (tenant único/múltiplo) 


| Oracle | 19c | O RHEL, o SuSe Linux | Autônomo (tenant único/múltiplo) 


| Oracle | 21c | O RHEL, o SuSe Linux | Autônomo (tenant único/múltiplo) 


| Oracle | 19c | O RHEL, o SuSe Linux | Independente com ASM (single/multitenant) 


| Oracle | 21c | O RHEL, o SuSe Linux | Independente com ASM (single/multitenant) 


| Oracle | 19c, 21c | O RHEL, o SuSe Linux | Data Guard 


| O PostgreSQL | O PostgreSQL 15 | A AMI do Amazon Linux 2023 | HA, instância independente 


| O PostgreSQL | O PostgreSQL 16 | A AMI do Amazon Linux 2023 | HA, instância independente 
|===


[[integrated-aws-services]]
== Serviços integrados da AWS

Os bancos de dados incluem os seguintes serviços integrados da AWS:

* CloudFormation
* O Simple Notification Service
* O CloudWatch
* O Systems Manager
* O Secrets Manager




[[regions]]
== Regiões

O Databases é compatível em todas as regiões comerciais onde o FSx for ONTAP é compatível. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Veja as regiões da Amazon suportadas."^]

As seguintes regiões da AWS não são suportadas:

* Regiões da China
* Secret Cloud
* Top Secret Cloud




[[getting-help]]
== Como obter ajuda

O Amazon FSx for NetApp ONTAP é uma solução própria da AWS. Para dúvidas ou problemas de suporte técnico associados ao seu sistema de arquivos FSx for ONTAP, à infraestrutura ou a qualquer solução que use esse serviço, use a Central de Suporte no seu AWS Management Console para abrir um caso de suporte com a AWS. Selecione o serviço "FSx for ONTAP" e a categoria apropriada. Forneça as informações restantes necessárias para criar seu caso de suporte da AWS.

Para perguntas gerais sobre o Workload Factory ou sobre os aplicativos e serviços do Workload Factory, consulte link:../get-help.html["Obtenha ajuda para o NetApp Workload Factory for Databases"].
